spring.cloud.stream:
  function:
    definition: dummy1Processor
  bindings:
    dummy1Processor-in-0:
      destination: dummy-event
    dummy1Processor-out-0:
      destination: order-updated
  kafka:
    binder:
      replication-factor: 1