spring.cloud.stream:
  function:
    definition: dummy2Processor
  bindings:
    dummy2Processor-in-0:
      destination: dummy-event
    dummy2Processor-out-0:
      destination: order-updated
  kafka:
    binder:
      replication-factor: 1